<?php
/**
 * ApartmentImageManager
 * This class has been auto-generated by Itirra
 */
require_once APPPATH . 'logic/base/BaseManager.php';
class ApartmentImageManager extends BaseManager {

  /** Fields. */
  public $fields = array("apartment_id" => array("type" => "select", "class" => "required", "options" => array()),
                         "image_id" => array("type" => "image", "class" => "required"),
                         "priority" => array("type" => "input_integer"));

  /** List params. */
  public $listParams = array("priority");

}