<?php
/*
 *  $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the LGPL. For more information, see
 * <http://www.doctrine-project.org>.
 */

/**
 * Doctrine_Import_ManagersBuilder
 *
 */
class Doctrine_Import_ManagersBuilder extends Doctrine_Import_Builder
{

  protected $_baseManager = 'BaseManager';


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::loadTemplate()
   */
  public function loadTemplate()
  {
    self::$_tpl = '/**'
    . '%s' . PHP_EOL
    . ' */' . PHP_EOL
    . '%s'
    . '%sclass %s extends %s {' . PHP_EOL
    . '%s' . PHP_EOL
    . '%s' . PHP_EOL
    . '}';
  }


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::buildPhpDocs()
   */
  public function buildPhpDocs(array $definition)
  {
    $ret = array();

    $ret[] = $definition['className'];
    $ret[] = 'This class has been auto-generated by Itirra';
    $ret = ' * ' . implode(PHP_EOL . ' * ', $ret);
    $ret = ' ' . trim($ret);

    return $ret;
  }


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::buildDefinition()
   */
  public function buildDefinition(array $definition)
  {
    if ( ! isset($definition['className'])) {
      throw new Doctrine_Import_Builder_Exception('Missing class name.');
    }
    $abstract = isset($definition['abstract']) && $definition['abstract'] === true ? 'abstract ':null;
    $className = $definition['className'];
    
    $actAs = null;
    if (isset($definition['actAs'])) {
      if (is_array($definition['actAs'])) {
        $actAs = array_keys($definition['actAs']);
      }
    }
    
    if ($actAs && in_array('NestedSet', $actAs)) {
      $extends = 'BaseTreeManager';
    } else {
      $extends = isset($definition['inheritance']['extends']) ? $definition['inheritance']['extends'] . 'Manager': $this->_baseManager;
    }

    if ( ! (isset($definition['no_definition']) && $definition['no_definition'] === true)) {
      $tableDefinitionCode = $this->buildTableDefinition($definition);
      $setUpCode = '';//$this->buildSetUp($definition);
    } else {
      $tableDefinitionCode = null;
      $setUpCode = null;
    }

    $docs = PHP_EOL . $this->buildPhpDocs($definition);
    
    $require = "require_once APPPATH . 'logic/base/" . $extends . ".php';" . PHP_EOL;

    $content = sprintf(self::$_tpl, $docs, $require, $abstract,
    $className,
    $extends,
    $tableDefinitionCode,
    $setUpCode);
     
    return $content;
  }


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::buildRecord()
   */
  public function buildTableDefinition(array $definition)
  {
    $code = $this->buildFieldsForManager($definition);
    $code = trim($code);
    if ($code) {
      $code1 = PHP_EOL . '  /** Fields. */';
      $code = $code1 . PHP_EOL . '  public $fields = array(' . $code;
    }
    return $code;
  }


  /**
   * buildColumns
   *
   * @param string $array
   * @return void
   */
  public function buildFieldsForManager(array $definition)
  {

    if (isset($definition['inheritance']['type']) && ($definition['inheritance']['type'] == 'simple' || $definition['inheritance']['type'] == 'column_aggregation')) {
      return "";
    }

    $columns = $definition['columns'];
    $columnsArr = array();

    $relations = array();
    if (isset($definition['relations'])) {
      foreach ($definition['relations'] as $relName => $rel) {
        $relations[] = $rel['local'];
      }
    }


    $types = array('string' => 'input');

    $arr = array();
    $i = 0;
    $build = null;
    foreach ($columns as $name => $column) {
      $columnName = isset($column['name']) ? $column['name']:$name;

      // Skip primary column
      if (isset($column['primary']) && $column['primary'] == TRUE) {
        continue;
      }

      $classes = array();

      // Process NOTNULL
      if (isset($column['notnull']) && $column['notnull'] == TRUE && !isset($column['default'])) {
        $classes[] = 'required';
      }

      $attrs = '';
      $type = $column['type'];

      // Check whether it is a relation
      if (in_array($columnName, $relations)) {

        if (strpos($columnName, 'image') !== FALSE) {
          $type = 'image';
        } else {
          $type = 'select';
          $attrs = '"options" => array()';
        }


      } else {
        $columnsArr[] = $columnName;

        // Process Strings
        if ($column['type'] == 'string') {
          if ($column['length'] <= 255) {
            $type = 'input';
            $attrs = '"attrs" => array("maxlength" => ' . $column['length'] . ')';
          } else {
            $type = 'textarea';
            $classes[] = 'charCounter';
          }
        }

        // Process Clobs
        if ($column['type'] == 'clob') {
          $type = 'textarea';
          $attrs = '"attrs" => array("maxlength" => ' . $column['length'] . ')';
          $classes[] = 'charCounter';
        }

        // Process Boolean
        if ($column['type'] == 'boolean') {
          $type = 'checkbox';
          $classes = array();
        }

        // Process Date
        if ($column['type'] == 'date') {
          $type = 'date';
        }

        // Process Enum
        if ($column['type'] == 'enum') {
          $type = 'select';
          $attrs = '"options" => array("' . implode('", "', $column['values']) .  '")';
        }

        // Process integer
        if ($column['type'] == 'integer') {
          $type = 'input_integer';
        }        
        
        // Process double
        if ($column['type'] == 'double') {
          $type = 'input_double';
        }           

        // Process timestamp
        if ($column['type'] == 'timestamp') {
          $type = 'datetime';
        }

      }


      // Classes
      $class = '';
      if (count($classes) > 0) {
        $class = '"class" => "';
        foreach ($classes as $cls) {
          $class .= $cls . " ";
        }
        $class = trim($class);
        $class .= '"';
      }

      if (!empty($attrs) && !empty($class)) {
        $class .= ', ';
      }

      $type = '"type" => "' . $type . '"';
      if (!empty($attrs) || !empty($class)) {
        $type .= ', ';
      }

      $build = '"' . $columnName . '" => array(' . $type . $class . $attrs . ')';

      if ($i > 0) {
        $build = '                         ' . $build;
      }
      if ($i < count($columns) - 2) {
        $build .= ',';
      }
      $i++;
      $arr[] = $build;
    }

    $build = implode(PHP_EOL, $arr) . ');';

    $build .= PHP_EOL . PHP_EOL;
    $build .= '  /** List params. */' . PHP_EOL; 
    $build .= '  public $listParams = array("' . implode('", "', $columnsArr) . '");' ;

    return $build;
  }


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::buildRecord()
   */
  public function buildRecord(array $definition)
  {
    if ( ! isset($definition['className'])) {
      throw new Doctrine_Import_Builder_Exception('Missing class name.');
    }

    $definition['topLevelClassName'] = $definition['className'];

    $this->writeDefinition($definition);

  }


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::writeTableClassDefinition()
   */
  public function writeTableClassDefinition(array $definition, $path, $options = array())
  {
    if ($prefix = $this->_classPrefix) {
      $className = $prefix . $definition['tableClassName'];
      if ($this->_classPrefixFiles) {
        $fileName = $className . $this->_suffix;
      } else {
        $fileName = $definition['tableClassName'] . $this->_suffix;
      }
      $writePath = $path . DIRECTORY_SEPARATOR . $fileName;
    } else {
      $className = $definition['tableClassName'];
      $fileName = $className . $this->_suffix;
    }

    if ($this->_pearStyle) {
      $writePath = $path . DIRECTORY_SEPARATOR . str_replace('_', '/', $fileName);
    } else {
      $writePath = $path . DIRECTORY_SEPARATOR . $fileName;
    }

    $content = $this->buildTableClassDefinition($className, $definition, $options);

    Doctrine_Lib::makeDirectories(dirname($writePath));

    if ( ! file_exists($writePath)) {
      file_put_contents($writePath, $content);
    }
  }


  /**
   * overridden
   * @see lib/database/Doctrine/Import/Doctrine_Import_Builder::writeDefinition()
   */
  public function writeDefinition(array $definition)
  {
    $originalClassName = $definition['className'];

    $definitionCode = $this->buildDefinition($definition);

    $fileName = $this->_getFileName($originalClassName, $definition);

    Doctrine_Lib::makeDirectories($this->_path);
    $writePath = $this->_path . DIRECTORY_SEPARATOR . $fileName;

    
    if (isset($definition['package']) && !empty($definition['package'])) {
      $writePath = str_replace('logic', 'logic\\' . $definition['package'] , $writePath);
    }
    
    $code = "<?php";
    $code .= PHP_EOL . $definitionCode;

    if ($this->_eolStyle) {
      $code = str_replace(PHP_EOL, $this->_eolStyle, $code);
    }

    Doctrine_Lib::makeDirectories(dirname($writePath));

    
    if (isset($definition['generate_once']) && $definition['generate_once'] === true) {
      if ( ! file_exists($writePath)) {
        $bytes = file_put_contents($writePath, $code);
      }
    } else {
      $bytes = file_put_contents($writePath, $code);
    }

    if (isset($bytes) && $bytes === false) {
      throw new Doctrine_Import_Builder_Exception("Couldn't write file " . $writePath);
    }
  }
}